add yarn support

diff --git a/4/s2i/bin/assemble b/4/s2i/bin/assemble
--- a/4/s2i/bin/assemble
+++ b/4/s2i/bin/assemble
@@ -70,35 +70,41 @@ if [ -z "$NODE_ENV" ]; then
   fi
 fi
 
-if [ "$NODE_ENV" != "production" ]; then
-
-	echo "---> Building your Node application from source"
-	npm install
-
+if [ ! -z "$YARN_ENABLED" ]; then
+    echo "---> Using 'yarn install' with YARN_ARGS"
+    yarn install $YARN_ARGS
 else
+    if [ "$NODE_ENV" != "production" ]; then
 
-	echo "---> Installing all dependencies"
-	NODE_ENV=development npm install
+        echo "---> Building your Node application from source"
+        npm install
 
-	#do not fail when there is no build script
-	echo "---> Building in production mode"
-	npm run build --if-present
+    else
 
-	echo "---> Pruning the development dependencies"
-	npm prune
+        echo "---> Installing all dependencies"
+        NODE_ENV=development npm install
 
-	# Clear the npm's cache and tmp directories only if they are not a docker volumes
-	NPM_CACHE=$(npm config get cache)
-	if ! mountpoint $NPM_CACHE; then
-		echo "---> Cleaning the npm cache $NPM_CACHE"
-		npm cache clean
-	fi
-	NPM_TMP=$(npm config get tmp)
-	if ! mountpoint $NPM_TMP; then
-		echo "---> Cleaning the $NPM_TMP/npm-*"
-		rm -rf $NPM_TMP/npm-*
-	fi
+        #do not fail when there is no build script
+        echo "---> Building in production mode"
+        npm run build --if-present
 
+        echo "---> Pruning the development dependencies"
+        npm prune
+
+        # Clear the npm's cache and tmp directories only if they are not a docker volumes
+        NPM_CACHE=$(npm config get cache)
+        if ! mountpoint $NPM_CACHE; then
+            echo "---> Cleaning the npm cache $NPM_CACHE"
+            #As of npm@5 even the 'npm cache clean --force' does not fully remove the cache directory
+            rm $NPM_CACHE* -rf
+        fi
+        NPM_TMP=$(npm config get tmp)
+        if ! mountpoint $NPM_TMP; then
+            echo "---> Cleaning the $NPM_TMP/npm-*"
+            rm -rf $NPM_TMP/npm-*
+        fi
+
+    fi
 fi
 
 # Fix source directory permissions
